### ISSUE TITLE
Instructions  - Video Walkthrough

### ISSUE THREAD

**Issue by TornMarketing** [mautic/plugin-grapesjs-builder#10]
Hey Team,

Can we arrange a video walkthrough on this, I am hitting a few issues which I am assuming would be resolved if I knew some of the setup elements in more details

- Unable to upload images, also keen to understand how the image load will work with the existing libraries/directories 
- MJML, unable to see any option to upload/build/edit MJML code

**Comment by weismannweb** [comment]
Did you see this yet:

MJML Template File: https://github.com/mautic/mautic/issues/7360#issuecomment-664003448

Video Demo:  https://github.com/mautic/mautic/issues/7360#issuecomment-611566817   
and 
https://github.com/Webmecanik/plugin-grapesjs-builder#mjml-support

Sorry if you did already but thought I would mention those two things just in case.

**Comment by TornMarketing** [comment]
unpacked the mjml folder and it played with the names, MJML works nicely.
Just the images now don't upload from grapesjs

**Comment by alexhammerschmied** [comment]
The image upload issue was already solved by [#26](https://github.com/Webmecanik/plugin-grapesjs-builder/pull/26)
