### ISSUE TITLE
Mautic 3.x Gmail 404 broken image for images with spaces because of + instead of %20

### ISSUE THREAD

**Issue by weismannweb** [mautic/plugin-grapesjs-builder#24]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
So gmail uses a proxy to cache and show images in emails when viewed in the gmail online web client.  I think this happens in thunderbird too if using gmail but im not sure.  So gmail converts this:

https://foo.com/media/images/grapesjs/Actress%20FB.png  (basically a space: "Actress FB.png")

to this:

https://ci5.googleusercontent.com/proxy/hPdUa87WfRmi36f09yr7WmpU5hIsrKVQfMzDjvEcnlCL7LOW9oFO044mDT2PbvHBieB2VFPTK4pSagAccxAvIcq4MuLY3unB5Cpgu9j2MHXLvcVtkTNdWyfvT9KU=s0-d-e1-ft#https://foo.com/media/images/grapesjs/Actress+FB.png

This happens in the new grapejs builder but I imagine unless the other builders convert spaces in urls on upload then the other builders have the same issue.  I did validate the default builder DOES change the names of the files to remove spaces so it does not have this issue.  That being said the default builder gives images an ugly long alphanumeric strings which I dont think is good too if you want to find an image in your choose image dialogue box.

So the issue is that the image gives a 404 because this "Actress+FB.png" does not exist but this does "Actress FB.png" but thats not the image being requested by Gmail.

A quick fix is to rename the image or copy it and replace spaces with"+".

A long term fix is probably for all upload routines to editors it should replace spaces with - since its bad to upload files with spaces anyway as it is a bad web practice.  The problem is mautic end users don't know this and you cant control them so you have to hold their hands a little by doing it for them.  The other fix might be some kind of htaccess rule?  Not really sure if that's possible.

| Q   | A
| --- | ---
| Mautic version | 3.x.x
| PHP version | 7.3
| Browser | chrome

### Steps to reproduce
1. send email using grape js to a gmail address with image that has space in the name.
2. see image does not show in gmail
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by weismannweb** [comment]
This is a temporary fix: 

to get it to work using htaccess file
RewriteRule ^(.*)\+(.*)$ /$1\$2 [L] 

but the proper thing to do is to do a str_replace on the file name and replace spaces with underscores, uppercase with lowercase, any special chars with nothing.  If I can find time I will do that.

**Comment by RCheesley** [comment]
Would be great if you have any time @weismannweb but for the time being let's make sure that this is well documented!

**Comment by adiux** [comment]
@weismannweb die you fix this? I just tried to reproduce it and the empty spaces in the filename got automatically replaced by underscores
![image](https://user-images.githubusercontent.com/13075514/114272010-80735e80-9a14-11eb-82f2-6335267a7c5c.png)

**Comment by RCheesley** [comment]
Closing due to being unable to reproduce and lack of response
