### ISSUE TITLE
Pressing shift-C takes out of grapesjs editor

### ISSUE THREAD

**Issue by wizardeur** [mautic/plugin-grapesjs-builder#28]
Hi,

I just installed the plugin on Mautic 3.2.1. Plugin installed without any problems.
When I try to the builder either in new mail or new landing page and I use shift-c combination I'm taken out of the editor and into the contacts.

**Comment by wizardeur** [comment]
Some more debugging, it seems that all global shortcuts do that are taking over the input.

**Comment by weismannweb** [comment]
Are you sure you have the latest package?  I removed those shortcuts a few weeks ago.

**Comment by wizardeur** [comment]
I downloaded the following: https://github.com/Webmecanik/plugin-grapesjs-builder/archive/mautic3x.zip
Is that the latest one?

**Comment by weismannweb** [comment]
No my code is not in that.  I think you need to download master. https://github.com/Webmecanik/plugin-grapesjs-builder/archive/master.zip it is more blleeding edge but has my fix.

**Comment by wizardeur** [comment]
Doesn't work with Mautic 3. I get PHP Fatal error:  Uncaught Error: Class 'MauticPlugin\IntegrationsBundle\Bundle\AbstractPluginBundle' not found in /var/www/bedziekryzys-mautic/m/plugins/GrapesJsBuilderBundle/GrapesJsBuilderBundle.php:9

**Comment by weismannweb** [comment]
ok then make the changes i made in my pull requests to the working version you have:

https://github.com/Webmecanik/plugin-grapesjs-builder/pulls?q=is%3Apr+author%3Aweismannweb

**Comment by wizardeur** [comment]
I did just that. I checked that the 3.x branch is not synchronized with master.

**Comment by alexhammerschmied** [comment]
Yes. This problem is related only to the 2.x branch. 
In 3.x it is solved already. 
I think it would be smart to close the work on the 2.x branch anyway and continue only with 3.x
