### ISSUE TITLE
email builder - dynamic content slot missing in mjml edition mode

### ISSUE THREAD

**Issue by npracht** [mautic/plugin-grapesjs-builder#3]
# Description
- [ ] Dynamic content missing for mjml edition
- [x] Test Dynamic content - Not data-param-dec-id set after save

**Comment by kuzmany** [comment]
When I worked times ago it was hard bring dynamic content for MJML templates
But workaround with less time effort could be enabled Dynamics Contact tab same like Code Mode do:

![image](https://user-images.githubusercontent.com/462477/107805277-6810fb80-6d65-11eb-9ec5-0fb3b3350f5c.png)


And then just use {dynamiccontent tokens in builder like other tokens

**Comment by RCheesley** [comment]
I think maybe this was an old issue? I was able to add the Dynamic Content slot and create variations.

Default:

![screenshot-mautic32 ddev site_8026-2021 02 14-00_13_08](https://user-images.githubusercontent.com/2930593/107864929-7d675200-6e59-11eb-881b-4597f5beeeb1.png)

Dynamic Content:

![screenshot-mautic32 ddev site_8026-2021 02 14-00_13_08](https://user-images.githubusercontent.com/2930593/107864933-82c49c80-6e59-11eb-8893-7f47e0d05b0c.png)

Screencast: https://youtu.be/VkXI5t-yczk

Closing the issue therefore, if I have missed the point please do correct me!
