### ISSUE TITLE
Editing a link inside a textblock is buggy

### ISSUE THREAD

**Issue by alexhammerschmied** [mautic/plugin-grapesjs-builder#32]
After inserting a link in a textblock it gets impossible to edit the link again. 
When double clicking on it the tooltip to visit the link freezes on the screen. And the text-options don't appear.

**Comment by adiux** [comment]
@alexhammerschmied Is this for email and pagebuilder?

**Comment by RCheesley** [comment]
I did not have this issue - clicking on the link in text blocks and clicking the link icon in the text editor opened up the edit screen to allow me to change the link - maybe I am missing something.
