### ISSUE TITLE
Include grapejs plugin in the Mautic core

### ISSUE THREAD

**Issue by adiux** [mautic/plugin-grapesjs-builder#38]

**Comment by RCheesley** [comment]
@kuzmany would you be able to make this PR to include this plugin in Mautic core? Hopefully it should be a small PR but would let us test in Mautibox I think!

**Comment by RCheesley** [comment]
This has been done with https://github.com/mautic/mautic/pull/9677 but we were too late to get it released tonight. 3.3 will come out tomorrow as a result - including the builder.
