### ISSUE TITLE
Code Mode does not work If plugin is enabled

### ISSUE THREAD

**Issue by kuzmany** [mautic/plugin-grapesjs-builder#44]
Code Mode opened by GrapeJs edit as well.  Expect open good old Code Mode builder

**Comment by RCheesley** [comment]
Confirmed that Code Mode is not working as we would expect. Firstly #50 is an issue but when Code Mode is available to be selected it is opening the builder with the other available template being loaded.

**Comment by RCheesley** [comment]
Interestingly it works better in the Landing Page builder - it opened up a blank canvas for me there: 

![screenshot-nimbus-capture-2021 02 13-23_42_12](https://user-images.githubusercontent.com/2930593/107864541-29f30500-6e55-11eb-8776-948d6304f0eb.png)

**Comment by RCheesley** [comment]
#41 resolves the issue of not being able to close the builder that I raised above!

**Comment by kuzmany** [comment]
I meant this Code Mode 

![image](https://user-images.githubusercontent.com/462477/107873210-268d6700-6eb1-11eb-87f0-07c0ed7ae440.png)

**Comment by powertictech** [comment]
same

**Comment by RCheesley** [comment]
@powertictech any chance you could take a look at fixing?

**Comment by RCheesley** [comment]
A question we had raised in the builder calls was whether it is necessary to retain Code Mode here, when we have a full code mode functionality within the GrapesJS builder itself?

**Comment by kuzmany** [comment]
@RCheesley good question. I think some people prefer code mode. I am not sure If GrapesJS is able to handle any kind of HTML structure without broke something. Maybe I am wrong...

**Comment by RCheesley** [comment]
Closing this in favour of https://github.com/mautic/mautic/issues/9988
