### ISSUE TITLE
builder.js:1 Uncaught SyntaxError: Identifier 'mjmlToHtml' has already been declared

### ISSUE THREAD

**Issue by adiux** [mautic/plugin-grapesjs-builder#48]
Creating a new email gives a Javascript syntax error: Identifier 'mjmlToHtml' has already been declared

![image](https://user-images.githubusercontent.com/13075514/107852212-dd390b00-6e0f-11eb-9114-4efd9ead05a5.png)

**Comment by RCheesley** [comment]
Is this still an issue? I am not able to reproduce on the current Features branch with the latest from the plugin so I think that it has been resolved with the #46 PR?
