### ISSUE TITLE
Builder does not allow code mode as an option where no compatible theme is available

### ISSUE THREAD

**Issue by RCheesley** [mautic/plugin-grapesjs-builder#50]
Noticed that when there is no compatible theme available it is not possible to see Code Mode, which makes no sense:

![screenshot-mautic32 ddev site-2021 02 13-23_30_36](https://user-images.githubusercontent.com/2930593/107864370-7f2e1700-6e53-11eb-82d7-313ca87c50c6.png)

**Comment by kuzmany** [comment]
I don't think this is big issue. This situation should not happen. 
Developer should with builder support bring also supported themes.
