### ISSUE TITLE
Landing page has no builder button until you press 'apply'

### ISSUE THREAD

**Issue by RCheesley** [mautic/plugin-grapesjs-builder#51]
In the email builder we have a Builder button from as soon as the create email screen opens:

![screenshot-mautic32 ddev site-2021 02 13-23_32_06](https://user-images.githubusercontent.com/2930593/107864435-ffed1300-6e53-11eb-98a9-b78aeabff310.png)

In the landing page builder this does not show, which is rather confusing, until we press apply.

![screenshot-mautic32 ddev site-2021 02 13-23_32_40](https://user-images.githubusercontent.com/2930593/107864449-18f5c400-6e54-11eb-9112-ec6548748db3.png)

**Comment by RCheesley** [comment]
This is addressed by #60

**Comment by RCheesley** [comment]
Re-opening this issue as it is persisting on landing pages after we merged #60 so does not seem to have been fully addressed.

**Comment by adiux** [comment]
Should be fixed with: https://github.com/mautic/mautic/pull/9841
