### ISSUE TITLE
How extend Grapes Sections / Blocks

### ISSUE THREAD

**Issue by luizeof** [mautic/plugin-grapesjs-builder#58]
how will the API be made so that we can extend the plugin with new blocks? 

would it be at the Mautic level with a specific plugin or can we extend it through themes?

Since the blocks are made in javascript / json, it would be interesting to be able to inject in the editor through themes.

**Comment by RCheesley** [comment]
https://grapesjs.com/docs/modules/Blocks.html does this help?

**Comment by luizeof** [comment]
@RCheesley yes, but how inject on mautic editor ?

**Comment by adiux** [comment]
Do we know how it works with WP/Gutenberg blocks?

**Comment by kuzmany** [comment]
It's not possible extend by plugin.

You can add additional blocks/Settings to builder.js. Something like 
https://github.com/mautic/plugin-grapesjs-builder/blob/mautic3x/Assets/library/js/builder.js#L267

The main sets of slots and sections is generated by **gjs-preset-newsletter** https://github.com/artf/grapesjs-preset-newsletter and **grapesjs-preset-mautic** https://github.com/Webmecanik/grapesjs-preset-mautic (there are steps to build js)

But all this changes require devs with experience with this kind of scripting.
