### ISSUE TITLE
MJML : <mj-font> in  <mj-head> doesn't make that font available for the editor 

### ISSUE THREAD

**Issue by jonathandhn** [mautic/plugin-grapesjs-builder#62]
How could I load a custom font (a single one actually) with my own MJML template ? I need to enforce Roboto.

I must edit the code or clone a block right now to achieve this.

`<mjml>
  <mj-head>
    <mj-font name="Roboto" href="https://fonts.googleapis.com/css?family=Roboto" />
  </mj-head>
  <mj-body>
    <mj-section>
      <mj-column>
        <mj-text font-family="Roboto, Arial">
          Hello World!
        </mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>`

**Comment by RCheesley** [comment]
Here is the MJML documentation which explains how to bring in a specific font: https://mjml.io/documentation/#mj-font

According to the code block in the docs:

```
 <mjml>
   <mj-head>
     <mj-font name="Raleway" href="https://fonts.googleapis.com/css?family=Raleway" />
   </mj-head>
   <mj-body>
     <mj-section>
       <mj-column>
         <mj-text font-family="Raleway, Arial">
           Hello World!
         </mj-text>
       </mj-column>
      </mj-section>
   </mj-body>
 </mjml>
```

Would you like to help us write some docs on how to create MJML themes @jonathandhn ?

**Comment by RCheesley** [comment]
See also this which may help: 

https://github.com/artf/grapesjs/issues/857
