### ISSUE TITLE
Emails build  with old builder are open with GrapeJS in M4

### ISSUE THREAD

**Issue by kuzmany** [mautic/plugin-grapesjs-builder#69]
Does it correct? Should we stay let open content with old builder, or force it to GrapeJs?

**Comment by RCheesley** [comment]
We just discussed this in the last call - there is a dev overhead which we did not have the time to implement to have the builders be able to say that they support multiple builders (eg legacy and GrapesJS).

We decided that it would be a better user experience if GrapesJS did support both legacy and GrapesJS themes when we make it enabled by default.

**Comment by kuzmany** [comment]
Ok. Thanks for clarify. Make sense
