### ISSUE TITLE
Block Button

### ISSUE THREAD

**Issue by gustavokeidel** [mautic/plugin-grapesjs-builder#81]
Hi everyone!

I have a problem with space betwen words in block "button". I trying space of keyboard and don't work.

![1234112](https://user-images.githubusercontent.com/66110864/116138910-ccc4cc80-a6ab-11eb-8b89-c5a81bcff31d.JPG)

thanks for all!

**Comment by adiux** [comment]
Duplicate: https://github.com/mautic/plugin-grapesjs-builder/issues/27
